#!/usr/bin/env python3
# -*- python -*-
# -*- coding: utf-8 -*-
#
# (c) 2013-2019 parasim inc
# (c) 2010-2019 california institute of technology
# all rights reserved
#
# Author(s): Lijun Zhu

# get the package
import altar
import altar.cuda
import altar.models.seismic.cuda

# make a specialized app that uses this model by default
class cudaStatic(altar.shells.cudaapplication, family='altar.applications.cudastatic'):
    """
    A specialized AlTar application that exercises the static inversion (linear) model
    """

    # user configurable state
    model = altar.cuda.models.model()
    model.default = altar.models.seismic.cuda.static()
    model.doc = "the AlTar model to sample"


# bootstrap
if __name__ == "__main__":
    # build an instance of the default app
    app = cudaStatic(name="cudastatic")
    # invoke the main entry point
    status = app.run()
    # share
    raise SystemExit(status)


# end of file
